// <auto-generated />
using System;
using Kompass.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kompass.Persistence.Migrations
{
    [DbContext(typeof(KompassDbContext))]
    [Migration("20260727160844_AddErgaenzbareProjektdaten")]
    partial class AddErgaenzbareProjektdaten
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Kompass.Domain.B56.Bauteilcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Bauteilcodes", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.B56.Import.B56ImportDatei", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportZeitpunkt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("B56ImportDateien", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.B56.Import.B56ImportZeile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("B56ImportDateiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bauteilcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("B56ImportDateiId");

                    b.ToTable("B56ImportZeilen", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Economics.Kostenposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kostenart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModernisierungsalternativeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModernisierungsalternativeId");

                    b.ToTable("Kostenpositionen", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Projects.AlternativeBauteil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BauteilcodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bemerkung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModernisierungsalternativeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BauteilcodeId");

                    b.HasIndex("ModernisierungsalternativeId");

                    b.ToTable("AlternativeBauteile", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Modernisierungsalternative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("B56Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstImAktuellenB56SnapshotVorhanden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Kurztext")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QuellSnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.ToTable("Modernisierungsalternativen", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Projekt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bearbeitungsstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("InterneBezeichnung")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjektmodellVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("QuellSnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projekte", (string)null);
                });

            modelBuilder.Entity("Kompass.Persistence.Data.Entities.B56ImportEintragEntity", b =>
                {
                    b.Property<Guid>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Archivdateipfad")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("BestaetigtAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dateiendung")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("DateigroesseBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FachdatenJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportiertAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Originaldateiname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("legacy");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Projektname")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotSchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("SnapshotStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("VerworfenAm")
                        .HasColumnType("TEXT");

                    b.HasKey("ImportId");

                    b.HasIndex("ImportiertAm");

                    b.HasIndex("ProjektId");

                    b.HasIndex("ProjektId", "Sha256");

                    b.ToTable("B56ImportEintraege", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.B56.Import.B56ImportZeile", b =>
                {
                    b.HasOne("Kompass.Domain.B56.Import.B56ImportDatei", null)
                        .WithMany("Zeilen")
                        .HasForeignKey("B56ImportDateiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kompass.Domain.Economics.Kostenposition", b =>
                {
                    b.HasOne("Kompass.Domain.Projects.Modernisierungsalternative", null)
                        .WithMany("Kostenpositionen")
                        .HasForeignKey("ModernisierungsalternativeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kompass.Domain.Projects.AlternativeBauteil", b =>
                {
                    b.HasOne("Kompass.Domain.B56.Bauteilcode", "Bauteilcode")
                        .WithMany()
                        .HasForeignKey("BauteilcodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kompass.Domain.Projects.Modernisierungsalternative", null)
                        .WithMany("Bauteile")
                        .HasForeignKey("ModernisierungsalternativeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bauteilcode");
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Modernisierungsalternative", b =>
                {
                    b.HasOne("Kompass.Domain.Projects.Projekt", null)
                        .WithMany("Alternativen")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kompass.Domain.B56.Import.B56ImportDatei", b =>
                {
                    b.Navigation("Zeilen");
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Modernisierungsalternative", b =>
                {
                    b.Navigation("Bauteile");

                    b.Navigation("Kostenpositionen");
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Projekt", b =>
                {
                    b.Navigation("Alternativen");
                });
#pragma warning restore 612, 618
        }
    }
}
