// <auto-generated />
using System;
using Kompass.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kompass.Persistence.Migrations
{
    [DbContext(typeof(KompassDbContext))]
    [Migration("20260730092438_AddB56KonfliktAlterNeuerWert")]
    partial class AddB56KonfliktAlterNeuerWert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Kompass.Domain.B56.Bauteilcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Bauteilcodes", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.B56.Import.B56ImportDatei", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportZeitpunkt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("B56ImportDateien", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.B56.Import.B56ImportZeile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("B56ImportDateiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bauteilcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("B56ImportDateiId");

                    b.ToTable("B56ImportZeilen", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Economics.EnergietraegerAnnahme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Co2Faktor")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Co2Preis")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Co2Preissteigerungsrate")
                        .HasPrecision(8, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EndenergieAlternative")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EndenergieIstZustand")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Energietraeger")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preis")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preissteigerungsrate")
                        .HasPrecision(8, 6)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WirtschaftlichkeitsannahmenId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WirtschaftlichkeitsannahmenId");

                    b.ToTable("EnergietraegerAnnahmen", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Economics.Kostenposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kostenart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModernisierungsalternativeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModernisierungsalternativeId");

                    b.ToTable("Kostenpositionen", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Economics.Wirtschaftlichkeitsannahmen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Basis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Betrachtungszeitraum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Diskontsatz")
                        .HasPrecision(8, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Foerderung")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Inflationsrate")
                        .HasPrecision(8, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("JaehrlicheWartungsmehrkosten")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModernisierungsalternativeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nutzungsdauer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModernisierungsalternativeId", "Basis")
                        .IsUnique();

                    b.ToTable("Wirtschaftlichkeitsannahmen", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Funding.Foerderprogramm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foerdergegenstand")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Foerdersatz")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Hoechstbetrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kumulierbarkeit")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pflichtnachweise")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Programmkennung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Quellenstand")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnischeMindestanforderungen")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zielgruppe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GueltigAb");

                    b.HasIndex("Programmkennung", "Version")
                        .IsUnique();

                    b.ToTable("Foerderprogramme", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Funding.FoerderquoteRegel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezugsbasis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoerderprogrammId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quote")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoerderprogrammId");

                    b.ToTable("FoerderquoteRegeln", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Funding.FoerderungZuordnung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoerderprogrammId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModernisierungsalternativeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModernisierungsalternativeId");

                    b.HasIndex("ModernisierungsalternativeId", "FoerderprogrammId")
                        .IsUnique();

                    b.ToTable("FoerderungZuordnungen", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Funding.Gueltigkeitsregel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Bezug")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FoerderprogrammId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoerderprogrammId");

                    b.ToTable("Gueltigkeitsregeln", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Funding.HoechstbetragRegel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezugsbasis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoerderprogrammId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Waehrung")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoerderprogrammId");

                    b.ToTable("HoechstbetragRegeln", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Funding.Kumulierbarkeitsregel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoerderprogrammId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoerderprogrammId");

                    b.ToTable("Kumulierbarkeitsregeln", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Funding.PflichtnachweisRegel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoerderprogrammId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstPflicht")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zeitpunkt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoerderprogrammId");

                    b.ToTable("PflichtnachweisRegeln", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Projects.AlternativeBauteil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BauteilcodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bemerkung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModernisierungsalternativeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BauteilcodeId");

                    b.HasIndex("ModernisierungsalternativeId");

                    b.ToTable("AlternativeBauteile", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Modernisierungsalternative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("B56Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstImAktuellenB56SnapshotVorhanden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Kurztext")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QuellSnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.ToTable("Modernisierungsalternativen", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Projekt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ansprechpartner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Auftraggeber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Bearbeitungsstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Gebaeudeart")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InterneBezeichnung")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postleitzahl")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjektmodellVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("QuellSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Strasse")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projekte", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Verbrauch.VerbrauchsDaten", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abweichungsursache")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnpassungsBegruendung")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AnpassungsFaktor")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("B56VergleichsWert")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Energietraeger")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Flaeche")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kosten")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Menge")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodeBis")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodeVon")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WitterungsbereinigungsFaktor")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.HasIndex("ProjektId", "PeriodeVon", "PeriodeBis", "Energietraeger");

                    b.ToTable("VerbrauchsDaten", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.Waermebruecken.Waermebruecke", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beiblatt2Referenz")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Berichtsdarstellung")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detailreferenz")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FRsi")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fremdnummer")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GleichwertigkeitStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("InterneNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Laenge")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Planreferenz")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pruefanmerkung")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PsiWert")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ThermCadReferenz")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Typ")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.HasIndex("ProjektId", "InterneNummer")
                        .IsUnique();

                    b.ToTable("Waermebruecken", (string)null);
                });

            modelBuilder.Entity("Kompass.Persistence.Data.Entities.B56ImportEintragEntity", b =>
                {
                    b.Property<Guid>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Archivdateipfad")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("BestaetigtAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dateiendung")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("DateigroesseBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FachdatenJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportiertAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Originaldateiname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("legacy");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Projektname")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotSchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("SnapshotStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("VerworfenAm")
                        .HasColumnType("TEXT");

                    b.HasKey("ImportId");

                    b.HasIndex("ImportiertAm");

                    b.HasIndex("ProjektId");

                    b.HasIndex("ProjektId", "Sha256");

                    b.ToTable("B56ImportEintraege", (string)null);
                });

            modelBuilder.Entity("Kompass.Persistence.Data.Entities.B56KonfliktEintragEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Aenderung")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlterWert")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bereich")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Entscheidung")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EntschiedenAm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feld")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NachfolgerImportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NeuerWert")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Schluessel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VorgaengerImportId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId", "NachfolgerImportId");

                    b.HasIndex("ProjektId", "VorgaengerImportId", "NachfolgerImportId");

                    b.HasIndex("ProjektId", "VorgaengerImportId", "NachfolgerImportId", "Bereich", "Schluessel", "Feld")
                        .IsUnique();

                    b.ToTable("B56KonfliktEintraege", (string)null);
                });

            modelBuilder.Entity("Kompass.Persistence.Data.Entities.B56SnapshotVergleichEntity", b =>
                {
                    b.Property<Guid>("VergleichId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HatAenderungen")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NachfolgerSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VergleichJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VorgaengerSnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("VergleichId");

                    b.HasIndex("ProjektId", "VorgaengerSnapshotId", "NachfolgerSnapshotId")
                        .IsUnique();

                    b.ToTable("B56SnapshotVergleiche", (string)null);
                });

            modelBuilder.Entity("Kompass.Domain.B56.Import.B56ImportZeile", b =>
                {
                    b.HasOne("Kompass.Domain.B56.Import.B56ImportDatei", null)
                        .WithMany("Zeilen")
                        .HasForeignKey("B56ImportDateiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kompass.Domain.Economics.EnergietraegerAnnahme", b =>
                {
                    b.HasOne("Kompass.Domain.Economics.Wirtschaftlichkeitsannahmen", null)
                        .WithMany("EnergietraegerAnnahmen")
                        .HasForeignKey("WirtschaftlichkeitsannahmenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kompass.Domain.Economics.Kostenposition", b =>
                {
                    b.HasOne("Kompass.Domain.Projects.Modernisierungsalternative", null)
                        .WithMany("Kostenpositionen")
                        .HasForeignKey("ModernisierungsalternativeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kompass.Domain.Funding.FoerderquoteRegel", b =>
                {
                    b.HasOne("Kompass.Domain.Funding.Foerderprogramm", null)
                        .WithMany("Foerderquoten")
                        .HasForeignKey("FoerderprogrammId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kompass.Domain.Funding.Gueltigkeitsregel", b =>
                {
                    b.HasOne("Kompass.Domain.Funding.Foerderprogramm", null)
                        .WithMany("Gueltigkeitsregeln")
                        .HasForeignKey("FoerderprogrammId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kompass.Domain.Funding.HoechstbetragRegel", b =>
                {
                    b.HasOne("Kompass.Domain.Funding.Foerderprogramm", null)
                        .WithMany("Hoechstbetraege")
                        .HasForeignKey("FoerderprogrammId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kompass.Domain.Funding.Kumulierbarkeitsregel", b =>
                {
                    b.HasOne("Kompass.Domain.Funding.Foerderprogramm", null)
                        .WithMany("Kumulierbarkeitsregeln")
                        .HasForeignKey("FoerderprogrammId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kompass.Domain.Funding.PflichtnachweisRegel", b =>
                {
                    b.HasOne("Kompass.Domain.Funding.Foerderprogramm", null)
                        .WithMany("Pflichtnachweisregeln")
                        .HasForeignKey("FoerderprogrammId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kompass.Domain.Projects.AlternativeBauteil", b =>
                {
                    b.HasOne("Kompass.Domain.B56.Bauteilcode", "Bauteilcode")
                        .WithMany()
                        .HasForeignKey("BauteilcodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kompass.Domain.Projects.Modernisierungsalternative", null)
                        .WithMany("Bauteile")
                        .HasForeignKey("ModernisierungsalternativeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bauteilcode");
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Modernisierungsalternative", b =>
                {
                    b.HasOne("Kompass.Domain.Projects.Projekt", null)
                        .WithMany("Alternativen")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kompass.Domain.B56.Import.B56ImportDatei", b =>
                {
                    b.Navigation("Zeilen");
                });

            modelBuilder.Entity("Kompass.Domain.Economics.Wirtschaftlichkeitsannahmen", b =>
                {
                    b.Navigation("EnergietraegerAnnahmen");
                });

            modelBuilder.Entity("Kompass.Domain.Funding.Foerderprogramm", b =>
                {
                    b.Navigation("Foerderquoten");

                    b.Navigation("Gueltigkeitsregeln");

                    b.Navigation("Hoechstbetraege");

                    b.Navigation("Kumulierbarkeitsregeln");

                    b.Navigation("Pflichtnachweisregeln");
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Modernisierungsalternative", b =>
                {
                    b.Navigation("Bauteile");

                    b.Navigation("Kostenpositionen");
                });

            modelBuilder.Entity("Kompass.Domain.Projects.Projekt", b =>
                {
                    b.Navigation("Alternativen");
                });
#pragma warning restore 612, 618
        }
    }
}
